### ISSUE TITLE
How can we help?

### ISSUE THREAD

**Issue by nazmifr** [LibreScore/LibreScore#1]
Hey there, if this takes form dude you'll have made a project that was awaited for really long by a lot of people!

https://musescore.org/en/node/89476

https://musescore.com/groups/improving-musescore-com/discuss/5023850?page=1#comment-5019001

https://www.reddit.com/r/selfhosted/comments/bh7efm/is_there_any_selfhosted_app_for_sheet_musicguitar/

https://musescore.org/en/node/301036

https://musescore.org/en/node/279873

https://musescore.org/en/node/139506

...

So if I understand things correctly:

- you got the full dataset of musescore which means that all the work that has been made on their site for years by volunteers on classics and popular songs won't be lost like it would be the case if a new platform would spring up.

- this would be self-hosted so anyone could publish their partitions on their site without any risk of censorship and the "partitionner" could decide whether to publish publicly for anyone to enjoy or on their private site with their conditions and customizations

Is this the idea?

What can I do to help? (basic webdev skills)

What can anyone finding this repository do to help?

Do you already have a js score/midi/??? player in mind? Will one need be developped for this project?

Thanks again for your intiative, I've rarely seen someone singlehandedly sticking it to a big service-provider like you did.

**Comment by Kripesh4569** [comment]
Here to help.

**Comment by thetek42** [comment]
Hi, I'm a professional graphic designer and web/python developer. I would offer my services as graphic designer - everything needs a nice UI - and web development in case you need someone.
Just email me (mail address should be visible in my profile) so that we can get into touch :)

**Comment by veehz** [comment]
Here to help too.

**Comment by RubenVerg** [comment]
here to help!
do you need a skillset or smth?

**Comment by Martin-Eckleben** [comment]
Maybe this project is under law fire?

Muse Group is a recently founded, shady Cypriot shell company.
https://en.wikipedia.org/wiki/Muse_Group

They are doing this with Audacity right now as well.

https://github.com/audacity/audacity/pull/835
https://github.com/audacity/audacity/discussions/880
https://github.com/audacity/audacity/issues/844

A MuseScore / Muse Group Employee directly threatened this project:
https://github.com/Xmader/musescore-downloader/issues/5#issuecomment-704372864

**Comment by sealsrock12** [comment]
> Maybe this project is under law fire?

The Muse Group seems to be leaving us alone for now, although saying that they are taking legal action in `https://github.com/audacity/audacity/discussions/889#discussioncomment-735621` (in code blocks to avoid mentioning the issue).

Most of the legal drama happened in late 2020. According to Xmader, MuseScore hasn't taken any legal action in 2021.

**Comment by PeterNjeim** [comment]
Helping can be done by writing code, opening issues and reporting bugs, etc., just like any other project
