### ISSUE TITLE
[Proposal] Support ActivityPub in some way

### ISSUE THREAD

**Issue by ticotaco72** [LibreScore/LibreScore#10]

**Comment by 4ndv** [comment]
Isn't librescore designed to be offline-first? ActivityPub requires some sort of direct connection between the federations, it's not really meant to be p2p, but federated. Some sort of DHT would be more appropriate, IMO

**Comment by PeterNjeim** [comment]
LibreScore the website requires IPFS to function, it doesn't function offline unless the files are cached as far as I'm aware.
