### ISSUE TITLE
Website doesn't work

### ISSUE THREAD

**Issue by climbTheStairs** [LibreScore/LibreScore#12]
When I open <https://demo.librescore.org/#/>, the only thing I can see is the header, the "Sheet music. Free. Forever." banner, and a completely empty "Newest sheets" section.

If I replace it with a musescore.com link (e.g. <https://librescore.org/miguel_ingelbeen/nuvole-bianche---ludovico-einoudi>, I am greeted by a 404 page.

**Comment by sealsrock12** [comment]
LibreScore currently only shows scores you uploaded under "newest sheets." All scores are currently unlisted. Also, because we took down the dataset, the website probably doesn't even work anymore. MuseScore sync relied on the dataset.
