### ISSUE TITLE
made a musescore search engine

### ISSUE THREAD

**Issue by sussyadminlmao** [LibreScore/LibreScore#22]
https://replit.com/@seba777/webcrawler?embed=true

This took too long, thank you for publishing the datasets @Xmader 

put the score ID in the box, push submit, and it will give you the ipfs download link

<3

**Comment by sussyadminlmao** [comment]
not an issue, just wanted to share this with everyone

**Comment by PeterNjeim** [comment]
This reminds me of the discord bot I made in the LibreScore discord server, we shut it down 5 months ago in favor of the [LibreScore App](https://github.com/LibreScore/app-librescore). I forgot this dataset still existed lol
