### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by ryanidk** [LibreScore/LibreScore#29]

**Comment by hykilpikonna** [comment]
Can confirm

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/22280294/181380777-59cb910c-7afa-4720-88ff-641b51bd5776.png">

**Comment by PeterNjeim** [comment]
This project is no longer in development. Our current tools are developed at https://github.com/LibreScore/dl-librescore, but they don't serve the same purpose as this repo

**Comment by clarkfw** [comment]
> This project is no longer in development. Our current tools are developed at https://github.com/LibreScore/dl-librescore, but they don't serve the same purpose as this repo

@PeterNjeim Though the app-librescore  works fine on my PC, I'm curious about the status of librescore.org. It's still a demo in the moment. Are you having legal issues?

**Comment by PeterNjeim** [comment]
Please don't ask questions that have already been answered

> This project is no longer in development
