### ISSUE TITLE
lilypond support?

### ISSUE THREAD

**Issue by gustavolinux** [LibreScore/LibreScore#3]
Could you add support for lilypond files? There are a lot of people doing great scores on it and it would be very easy to get the .ly files and make the server generates the .midi and .pdf files.

**Comment by PeterNjeim** [comment]
This website is meant as a viewer of MSCZ files, not merely as a converter. Not only that, but there is no server (other than the one hosting the static site). Lilypond would need to be compiled for webassembly, and considerable effort would be needed to make it function as an npm package.
