### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Ubuntufanboy** [LibreScore/LibreScore#35]
# I hate to be that guy...

But seriously man! I know it sucks making documentation but how is anybody supposed to use it if it has no docs!!!!

**Comment by PeterNjeim** [comment]
Not sure why a website would need documentation. Click on upload, then upload your file, can't be any simpler than that.

Also, this project is no longer in development. Our current tools are developed at https://github.com/LibreScore/dl-librescore, but they don't serve the same purpose as this repo

**Comment by xeruf** [comment]
Great initiative!
Maybe you can replace the empty changelog and contributing file with a readme explaining the current state :)

**Comment by xeruf** [comment]
Also, you should unpin this repo from your organization page

**Comment by PeterNjeim** [comment]
> Great initiative!
> Maybe you can replace the empty changelog and contributing file with a readme explaining the current state :)

Not possible

**Comment by PeterNjeim** [comment]
> Also, you should unpin this repo from your organization page

Not possible

**Comment by PeterNjeim** [comment]
I'd recommend not asking people to do the obvious, because it implies we're too stupid to do it. I don't own this organization
