### ISSUE TITLE
Upload link leads to a 404 page

### ISSUE THREAD

**Issue by andy5995** [LibreScore/LibreScore#45]
I just found this project. Sounds interesting, but when I went to librescore.org and clicked the "upload" link, I was led to a 404 page.

**Comment by luzpaz** [comment]
Is this still relevant ?

**Comment by cw1997** [comment]
It is the same as I see.

**Comment by PeterNjeim** [comment]
This project is no longer in development. Our current tools are developed at https://github.com/LibreScore/dl-librescore, but they don't serve the same purpose as this repo
