### ISSUE TITLE
upload link on librescore.org is a 404

### ISSUE THREAD

**Issue by strk** [LibreScore/LibreScore#47]
This is possibly not the place to report this issue but didn't find a better place

**Comment by strk** [comment]
I should note that librescore.org is listed as the official website associated with this project so this is possibly a good place to report issues

**Comment by PeterNjeim** [comment]
This project is no longer in development. Our current tools are developed at https://github.com/LibreScore/dl-librescore, but they don't serve the same purpose as this repo
