### ISSUE TITLE
Too many clicks

### ISSUE THREAD

**Issue by FlashNoob98** [LibreScore/LibreScore#6]
Sorry I uploaded a file multiple time, rage-clicking the upload button, it seemed not loading at all, now there are multiple Shindler's List Flute scores 😅

**Comment by PeterNjeim** [comment]
It's all hosted on IPFS, no need to worry about it

**Comment by FlashNoob98** [comment]
how could I contrib to host a IPFS node? I'm searching the CID or something similiar for LibreScore database

**Comment by PeterNjeim** [comment]
You simply install IPFS on your computer and host files that are in the dataset. It won't help that much since this relies on Xmader's personal IPNS. LibreScore's other projects have since moved on from the dataset, you can see the modern projects here: https://github.com/LibreScore/dl-librescore
