### ISSUE TITLE
[Feature Request] Store the files locally

### ISSUE THREAD

**Issue by gorgobacka** [LibreScore/LibreScore#7]
I really like the idea to use ipfs for storing the files.

But I would also like to see the possibility to store the files locally. Than it would be possible to use this platform as a self-hosted solution for a small group of people sharing their sheet music privately.

**Comment by PeterNjeim** [comment]
I believe it's possible to use IPFS in a local way, one of many tutorials: https://medium.com/@s_van_laar/deploy-a-private-ipfs-network-on-ubuntu-in-5-steps-5aad95f7261b
