### ISSUE TITLE
Add support for translations.

### ISSUE THREAD

**Issue by Vilagamer999** [LibreScore/LibreScore#9]
Please add support for translations, I would gladly translate your app into Spanish.

**Comment by rpqt** [comment]
Same here, I can translate it in French if needed

**Comment by baptiste-perrier** [comment]
Can bring help for french translation

**Comment by PeterNjeim** [comment]
I don't have admin access to this repository, so I can't add the needed webhook to integrate with Weblate. If that ever happens, I'll share the link. Currently translations can be added by creating a JSON file in the `src/ui/i18n` folder, with the title being the ISO code for the language. For example, `es.json` would be for Spanish.
